use_frameworks!

target 'JumpingJacker_Example' do
  pod 'JumpingJacker', :path => '../'

  target 'JumpingJacker_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.0.0'
  pod 'Nimble', '~> 5.1.1'
  end
end
